#!/bin/bash
#
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

inbox=${dir}/notes/inbox

template=$(mktemp)
content=$(mktemp)

stamp=$(date +%Y%m%d%H%M%S)
cat ${dir}/config/idea.template | sed 's/%DATE%/'$stamp'/g' > $template

entrypoint=$(rg '^#' $template -n | head -n 1 | awk 'BEGIN {FS=":"} {print $1}')

cp $template $content
vi $content +${entrypoint}

slug=$(rg '^#' $content | head -n 1 | cut -c3- | sed 's/ /_/g' | sed 's/[^0-9a-zA-Z_]//g')

diff $template $content > /dev/null || {
	noteName=${stamp}_${slug}
	mv $content ${inbox}/${noteName}.md
	echo "Note ${noteName} added to inbox."
}
