#!/bin/bash
#
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

book_name=spanish_is_hard
epub_to_pdf=/Applications/calibre.app/Contents/MacOS/ebook-convert

mkdir -p ${dir}/out
rm -f ${dir}/out/${book_name}.epub
cd ${dir}/src && zip -0 -X ${book_name}.epub mimetype
cd ${dir}/src && zip -r ${book_name}.epub META-INF fonts images *.html content.opf *.css toc.ncx
mv ${dir}/src/${book_name}.epub ${dir}/out/${book_name}.epub
${epub_to_pdf} ${dir}/out/${book_name}.epub ${dir}/out/${book_name}.pdf
